apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "XgErX/NRUtzKnOldTWFkwW1kMJX7BfExkVgBYUA+pqo="
  NEXTAUTH_SECRET: "FEPRXlqOxvNqHvWuS3WOaXVy9fM8uTEt/ejvU3bbVBw="
